### ISSUE TITLE
Find a fix to show email graphics (now doesn't work with gmail)

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard#429]

**Comment by przemyslaw** [comment]
The Google Image Proxy server will fetch your images if this images:
- have extensions like .png, .jpg/.jpeg or .gif only. May be .webp too. But not [.svg](https://stackoverflow.com/q/20815613/).
- do not use any kind of query string part in the image URL like ?id=123
- have an URL which is mapped onto the image directly.
- have not a long name.

Requirements for image server:
- The response from image server/proxy server must include the correct header like Content-Type: image/jpeg.
- File extension and content-type header must be in the same type.
- Status code in server response must be 200 instead of 403, 500 and etc.

**Comment by przemyslaw** [comment]
Our images are .svg - probably that's the reason why they aren't stored on googles Image Proxy.
