### ISSUE TITLE
Project board automation

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard#446]
When doing "done" on this board, issues in the project repository are not closed.
We need project automation: https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/configuring-automation-for-project-boards

**Comment by przemyslaw** [comment]
That does not work that way - the automation is that when an issue or pull request is closed - the status of the item is set to DONE - and that we have enabled.
The other way would not work as one issue can be linked in many projects/boards.

This problem is reported here: https://github.com/orgs/community/discussions/7537 but not yet fixed.
