### ISSUE TITLE
Session is required

### ISSUE THREAD

**Issue by francois-pasquier** [DefGuard/defguard#494]
**Describe the bug**
When following documentation to setup defguard (either with the one liner or with the docker-compose template + custom env file), when logging with admin I am receiving this error:

```
docker-compose-core-1  | 2024-01-02T12:10:25.764081Z ERROR http_request{method=GET path=/api/v1/info}: defguard::handlers: Session is required
```

**To Reproduce**
1. Login with admin user
4. See error in logs

**Expected behavior**
No error

**Version information**
- Defguard Core version: [sha-3d84b24](https://github.com/orgs/defguard/packages/container/defguard/162900609?tag=sha-3d84b24)
  - Operating system and version running the gateway: Debian
 - Your browser and version: Chrome Canary / FIrefox

**Comment by amwdrizz** [comment]
Running into this error my self on a fresh Debian 12 server install with the latest docker components installed.  Cross tested UI login against Opera / Safari / Chrome.  All browsers yield the same result, no login occurs.  Looking in the browser console, it provides an 401 access denied error which corresponds with the same error seen in the core docker container when dumping its output using docker logs.  Looking at the session storage in the browsers there are no identifiers set that would indicate session data is stored in the browser upon successful login.

Deployment method was using the one-liner.

**Comment by mrbiz41** [comment]
Hi,

I got the same error yesterday. I deployed using docker-compose, and tried logging in with firefox 119 on windows. 

Thanks

**Comment by moubctez** [comment]
My guess is, you have to connect to http://localhost:8000, not http://127.0.0.1:8000.

**Comment by amwdrizz** [comment]
There is no port 8000 exposed from the docker containers when following the guide.

`CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS         PORTS                                                                                         NAMES
898e79587eb9   ghcr.io/defguard/defguard:sha-d9bdd10   "./defguard"             39 seconds ago   Up 4 seconds   0.0.0.0:50055->50055/tcp, :::50055->50055/tcp                                                 defguard-core-1
32f3f6391363   caddy:2.7-alpine                        "caddy run --config …"   39 seconds ago   Up 4 seconds   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 443/udp, 2019/tcp   defguard-caddy-1
38bfc47a4373   postgres:15-alpine                      "docker-entrypoint.s…"   39 seconds ago   Up 4 seconds   5432/tcp                                                                                      defguard-db-1`

Additionally localhost == 127.0.0.1 there is no difference between either or other than the written text.  The only time it would ever not work is if you messed with the hosts file and deleted the localhost lines from it.  Which you should never do as it would break other network items related to the OS itself.

**Comment by wojcik91** [comment]
Hi!
Thank you all for pointing this out.

What is the domain you are using as `DEFGUARD_URL`? Is HTTPS enabled?

I'm trying to track down the cause and for now it seems the issue is caused by cookie settings. When using a non-localhost domain  (like id.example.com) without HTTPS you have to also enable insecure cookies by setting `DEFGUARD_COOKIE_INSECURE` env variable in core to `true`. Otherwise the browser will reject our cookies.

Please let me know if this solves your issues. In the meantime I'll make an update to the script and deployment instructions.

**Comment by amwdrizz** [comment]
No, HTTPS was/is not enabled, nor am I using localhost.  I am using an publicly accessible domain like id.example.com; This is test/investigation instance to see if it is worth deploying fully or not (with ssl certs, etc).  So no direct public IPv4 address since again checking it out.

Using `DEFGUARD_COOKIE_INSECURE=true` in the docker-compose.yaml file did the trick.  I initially dropped that in the .env file and saw no change.  On a whim I re-examined the docker-compose file and added it there and redeployed.  That did the trick.

Having that outlined in the documents with a giant warning of only do this in dev/test and not in prod would be ideal more than likely.

**Comment by francois-pasquier** [comment]
`What is the domain you are using as DEFGUARD_URL? Is HTTPS enabled?`

I was testing the access with the ip of my server instead of the domain I specified.

Fixed it for me!
