### ISSUE TITLE
Design: Add an option to start several VPN to different locations simultaneously

### ISSUE THREAD

**Issue by dbutti** [DefGuard/defguard#604]
**Is your feature request related to a problem? Please describe.**
As soon as you start having multiple locations defined, it get impractical to start the VPN connections individually. And if there protected through MFA, it is a real pain.

**Describe the solution you'd like**
It should be possible to select multiple locations, or even all of them, and have the corresponding tunnels activated with a single action. MFA info is associated to the user anyway, so a single validation should be accepted to open all the tunnels in this way.

**Describe alternatives you've considered**

**Additional context**
I believe that users who have several locations defined will often need to stay connected to several of them at the same time. Maybe an additional concept of "location group" might make sense as well, allowing the user to connect/disconnect all the locations in a group with a single action.

**Comment by teon** [comment]
1. Autostart is one, but if there would be **one 2FA** it should be indicated that it will connect to the following VPN Locations....
2. Since we would have connecting automatically to several locations, would be great also to have it manually, and choose X number of locations, and click Connect once.

For all of that @4lb we would need UI/UX.

**Comment by teon** [comment]
Duplicate #606
