### ISSUE TITLE
Question about YOUR_PRIVATE_KEY when addUserDevice (via API)

### ISSUE THREAD

**Issue by velrino** [DefGuard/defguard#831]
Hi ,

I'm conducting an integration test with the DefGuard API and I have a question:

**Can the wireguard_pubkey be any string generated with SHA-256?**

![image](https://github.com/user-attachments/assets/60e33fd7-f137-42f6-acf9-2519f8746ab8)

Currently, I'm generating the key by combining the username with a timestamp string

I'm asking this because, after generating the CONFIG file on the user's page, the downloaded file includes
![image](https://github.com/user-attachments/assets/b21f8d5f-8c65-4d9a-97e2-7523daf80100)

```
[Interface]
PrivateKey = YOUR_PRIVATE_KEY
```

I identified this bug because I generated two files through the API and one through the web interface, and the issue only occurred in the web-generated file.

![image](https://github.com/user-attachments/assets/316775ee-d98d-46b8-aca1-ff09882dfe8a)

**To Reproduce**
1. Navigate to **/admin/users/USERNAME**, then in the **User Devices** section, click on the **cog** icon, and click**Show Configuration**
![image](https://github.com/user-attachments/assets/fba2d357-b048-43bd-80f5-511beed7940c)

2. After opening the **Device VPN configurations** modal, click the downward arrow to **download**
![image](https://github.com/user-attachments/assets/d6b3bb4b-112f-4893-ad42-360994a8a297)

**Comment by teon** [comment]
@velrino this is not a bug. Defguard is built with the **highest security standards in mind* - thus **we don't store user/devices** private keys.

That's why **our desktop client automatically generates private keys securely and locally** and only sends the public key to defguard.
If a user adds a **manual/vanilla WG** device in defguard - we have a secure key generation process **in the users browser** and **only send public keys to defguard.
