### ISSUE TITLE
SSO IDP for Free with Any provider

### ISSUE THREAD

**Issue by t4ov** [DefGuard/defguard#846]
Hello, 
  Are you considering to make SSO with any IDP for free? Tailscale and netbird released this feature completely free. 
https://netbird.io/knowledge-hub/accessible-mfa-implementation

Thanks

**Comment by teon** [comment]
Defguard has a built in SSO and is a full featured OpenID Connect provider, and has more extensions (like groups) - and that is complete free and open-source. By deploying defguard you have an SSO for all your apps and moreover one system and one account for Apps & VPN!

The enterprise license only covers external OIDC (like google workspace or Microsoft) which are typically used by companies/corporations - and if they do, they can afford our license and should support our open-source product - since they also support large corporations.
